version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
